<a href="https://colab.research.google.com/github/AlexeyTri/PyTorchTutorials/blob/main/Tutorial10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Activation function

In [118]:
import torch
import torch.nn as nn
import torch.nn.functional as F

output = w*x + b

output = activation_function(output)

In [119]:
x = torch.tensor([-1.0,1.0,2.0,3.0])

In [120]:
# softmax
output = torch.softmax(x, dim=0)
output

tensor([0.0120, 0.0889, 0.2418, 0.6572])

In [121]:
sm = nn.Softmax(dim=0)
output = sm(x)
output

tensor([0.0120, 0.0889, 0.2418, 0.6572])

In [122]:
# sigmoid
output = torch.sigmoid(x)
output

tensor([0.2689, 0.7311, 0.8808, 0.9526])

In [123]:
s = nn.Sigmoid()
output = s(x)
output

tensor([0.2689, 0.7311, 0.8808, 0.9526])

In [124]:
# tanh
output = torch.tanh(x)
output

tensor([-0.7616,  0.7616,  0.9640,  0.9951])

In [125]:
t = nn.Tanh()
output = t(x)
output

tensor([-0.7616,  0.7616,  0.9640,  0.9951])

In [126]:
# relu
output = torch.relu(x)
output

tensor([0., 1., 2., 3.])

In [127]:
relu = nn.ReLU()
output = relu(x)
output

tensor([0., 1., 2., 3.])

In [128]:
# leaky relu
output = F.leaky_relu(x)
output

tensor([-0.0100,  1.0000,  2.0000,  3.0000])

In [129]:
lrelu = nn.LeakyReLU()
output = lrelu(x)
output

tensor([-0.0100,  1.0000,  2.0000,  3.0000])

In [130]:
class NeuralNet1(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet1, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [131]:
class NeuralNet2(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet2, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size) 
        # self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, hidden_size)  
    
    def forward(self, x):
        out = torch.relu(self.linear1(x))
        out = torch.sigmoid(self.relu(out))
        return out